Repository dgu-fe-master/tech-talk, pull requests merged in 2023-08, with the labels that each got.

#1 8/19 tech talk
  2023-08-16/younho.md
Labels: 클린코드

#4 8/19 tech talk
  2023-08-16/wonho.md
Labels: 이미지 최적화

#3 8/19 tech talk
  2023-08-19/hyewon.md
Labels: React, 클로저
